#!/usr/bin/env python3
# -*- coding: utf-8 -*- 

from typing import Dict, List

submission_replies: Dict[str, List[str]] = {
    "tesla": [
        "Thread on how safe Tesla cars are",
        "We don’t control the federal reserve. The higher the rates, the harder they fall",
        "The fun police made us do it (sigh)",
        "We’ll go after the Wall St short-sellers, certain law firms & (sometimes) corrupt regulators who are the true evil."],
    "files": [
        "!!",
        "Interesting",
        "We need to move on from the Twitter Files"],
    "twitter": [
        "Pay me $8!",
        "$7 is a small price for freedom",
        "Looking into this.",
        "This is bizarre. Looking into it.",
        "Interesting",
        "\#SoBrave",
        "Parody & reality are becoming indistinguishable",
        "Concerning",
        "Extremely concerning",
        "Super concerning",
        "Strange",
        "It makes no sense",
        "Wow",
        "Odd",
        "That’s what she said",
        "Whatever you say, cutie \U0001F979",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Haha that would sickkk",
        "Negative feedback is a good thing",
        "Negative feedback received on this platform is great for reducing ego-based errors",
        "I appreciate the note. Frankly, negative feedback is good. Keeps ego in check.",
        "Frankly, I love the negative feedback on this platform. Vastly preferable to some sniffy censorship bureau!",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram",
        "\U0001F3AF", # bullseye
        "\U0001F4AF", # 100
        "\U0001F9BE", # mechanical arm
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "Accurate",
        "Precisely",
        "Exactly",
        "Really",
        "Obviously",
        "True",
        "Twitter is now trending to breakeven if we keep at it.",
        "Looks like this platform may see all time high device user seconds usage this week",
        "Maximizing unregretted user-seconds",
        "Our user-seconds have reached all time highs in recent months, so something is wrong. Will investigate.",
        "We’ve pushed harder for free speech than any other Internet company, including Wokipedia",
        "Try it, but don’t trust it yet.",
        "Twitter is a serious danger to their ability to control the narrative",
        "Something fundamental is wrong",
        "Something is wrong",
        "Titter was trending to lose ~$3B/year (revenue drop of ~$1.5B + debt servicing of ~$1.5B) and had $1B in cash, so only 4 months of money. Extremely dire situation.",
        "A trillion dollar market cap for this platform is not out of the question",
        "Extremely dire situation.",
        "Turns out we just needed to blow on the cartridge",
        "I get all my opinions from Twitter",
        "You are free to be your true self here",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "I never take notes",
        "It’s kinda flattering to be insulted on this site tbh",
        "I hope this platform increasingly brings you joy & elucidation",
        "Will greatly improve the esthetics.",
        "We are hell bent on making this platform the best place on Earth for great content creators!",
        "You’re terrible & I love you\n\n*not terrible",
        "Sometimes, when you learn about something, you think you have it",
        "Haha what a tool",
        "Incompetence, in the limit, is indistinguishable from sabotage",
        "Super big deal",
        "I prefer peace, but if they want war, they will get it"],
    " x ": [
        "Pay me $8!",
        "$7 is a small price for freedom",
        "Looking into this.",
        "This is bizarre. Looking into it.",
        "Interesting",
        "\#SoBrave",
        "Parody & reality are becoming indistinguishable",
        "Concerning",
        "Extremely concerning",
        "Super concerning",
        "Strange",
        "It makes no sense",
        "Wow",
        "Odd",
        "That’s what she said",
        "Whatever you say, cutie \U0001F979",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Haha that would sickkk",
        "Negative feedback is a good thing",
        "Negative feedback received on this platform is great for reducing ego-based errors",
        "I appreciate the note. Frankly, negative feedback is good. Keeps ego in check.",
        "Frankly, I love the negative feedback on this platform. Vastly preferable to some sniffy censorship bureau!",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram",
        "\U0001F3AF", # bullseye
        "\U0001F4AF", # 100
        "\U0001F9BE", # mechanical arm
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "Accurate",
        "Precisely",
        "Exactly",
        "Really",
        "Obviously",
        "True",
        "Twitter is now trending to breakeven if we keep at it.",
        "Looks like this platform may see all time high device user seconds usage this week",
        "Maximizing unregretted user-seconds",
        "Our user-seconds have reached all time highs in recent months, so something is wrong. Will investigate.",
        "We’ve pushed harder for free speech than any other Internet company, including Wokipedia",
        "Try it, but don’t trust it yet.",
        "Twitter is a serious danger to their ability to control the narrative",
        "Something fundamental is wrong",
        "Something is wrong",
        "Titter was trending to lose ~$3B/year (revenue drop of ~$1.5B + debt servicing of ~$1.5B) and had $1B in cash, so only 4 months of money. Extremely dire situation.",
        "A trillion dollar market cap for this platform is not out of the question",
        "Extremely dire situation.",
        "Turns out we just needed to blow on the cartridge",
        "I get all my opinions from Twitter",
        "You are free to be your true self here",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "I never take notes",
        "It’s kinda flattering to be insulted on this site tbh",
        "I hope this platform increasingly brings you joy & elucidation",
        "Will greatly improve the esthetics.",
        "We are hell bent on making this platform the best place on Earth for great content creators!",
        "You’re terrible & I love you\n\n*not terrible",
        "Sometimes, when you learn about something, you think you have it",
        "Haha what a tool",
        "Incompetence, in the limit, is indistinguishable from sabotage",
        "Super big deal",
        "I prefer peace, but if they want war, they will get it"],
    " bot": [
        "Looking into this.",
        "This is bizarre. Looking into it.",
        "Interesting",
        "Concerning",
        "Extremely concerning",
        "Super concerning",
        "Strange",
        "It makes no sense",
        "Wow",
        "Odd",
        "That’s what she said",
        "Whatever you say, cutie \U0001F979",
        "Negative feedback is a good thing",
        "Negative feedback received on this platform is great for reducing ego-based errors",
        "I appreciate the note. Frankly, negative feedback is good. Keeps ego in check.",
        "Frankly, I love the negative feedback on this platform. Vastly preferable to some sniffy censorship bureau!",
        "Something fundamental is wrong",
        "Something is wrong",
        "Extremely dire situation.",
        "Our user-seconds have reached all time highs in recent months, so something is wrong. Will investigate.",
        "Turns out we just needed to blow on the cartridge",
        "Just ~$100/month for API access with ID verification will clean things up greatly.",
        "We will defeat the spam bots or die trying!",
        "What we need is TruthGPT",
        "In the spirit of self-awareness, what are you?"],
    "bug ": [
        "Something fundamental is wrong",
        "Something is wrong",
        "Extremely dire situation.",
        "Our user-seconds have reached all time highs in recent months, so something is wrong. Will investigate.",
        "Turns out we just needed to blow on the cartridge",
        "This platform is so brittle (sigh). Will be fixed shortly.",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "A ground up rewrite is underway that simplifies the X codebase dramatically.",
        "A small API change had massive ramifications. The code stack is extremely brittle for no good reason."],
    " error": [
        "Negative feedback received on this platform is great for reducing ego-based errors",
        "I appreciate the note. Frankly, negative feedback is good. Keeps ego in check.",
        "Something fundamental is wrong",
        "Something is wrong",
        "Extremely dire situation.",
        "Our user-seconds have reached all time highs in recent months, so something is wrong. Will investigate.",
        "Turns out we just needed to blow on the cartridge",
        "This platform is so brittle (sigh). Will be fixed shortly.",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "A ground up rewrite is underway that simplifies the X codebase dramatically.",
        "A small API change had massive ramifications. The code stack is extremely brittle for no good reason."],
    "broken": [
        "Something fundamental is wrong",
        "Something is wrong",
        "Extremely dire situation.",
        "Our user-seconds have reached all time highs in recent months, so something is wrong. Will investigate.",
        "Turns out we just needed to blow on the cartridge",
        "This platform is so brittle (sigh). Will be fixed shortly.",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "A ground up rewrite is underway that simplifies the X codebase dramatically.",
        "A small API change had massive ramifications. The code stack is extremely brittle for no good reason."],
    "twitter down": [
        "Something fundamental is wrong",
        "Something is wrong",
        "Extremely dire situation.",
        "Our user-seconds have reached all time highs in recent months, so something is wrong. Will investigate.",
        "Turns out we just needed to blow on the cartridge",
        "This platform is so brittle (sigh). Will be fixed shortly.",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "A ground up rewrite is underway that simplifies the X codebase dramatically.",
        "A small API change had massive ramifications. The code stack is extremely brittle for no good reason."],
    "twitter is down": [
        "Something fundamental is wrong",
        "Something is wrong",
        "Extremely dire situation.",
        "Our user-seconds have reached all time highs in recent months, so something is wrong. Will investigate.",
        "Turns out we just needed to blow on the cartridge",
        "This platform is so brittle (sigh). Will be fixed shortly.",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "A ground up rewrite is underway that simplifies the X codebase dramatically.",
        "A small API change had massive ramifications. The code stack is extremely brittle for no good reason."],
    "culture": [
        "End of days vibes",
        "Although there are some bad things in the world, remember that there are many good things too"],
    "no plan": [
        "Amazing. You're a jackass!",
        "Haha what a tool"],
    "wealth": [
        "I’m rich, bitch!",
        "Amm rerrch, berrtch!",
        "$7 is a small price for freedom",
        "I grew up in a lower, transitioning to upper, middle income situation",
        "I grew up in a lower, transitioning to upper, middle income situation, but did not have a happy childhood.",
        "I grew up in a lower, transitioning to upper, middle income situation, but did not have a happy childhood. Haven’t inherited anything ever from anyone, nor has anyone given me a large financial gift."],
    "misinformation": [
        "This is not a right wing takeover, but rather a centrist takeover.",
        "Interesting",
        "Comedy is now legal on Twitter.",
        "We should stop canceling comedy!",
        "Funny cause it’s true",
        "New Twitter is the source of truth",
        "Twitter is the source of truth",
        "Twitter needs to become by far the most accurate source of information about the world. That’s our mission.",
        "Fight for truth, whole truth & nothin but!",
        "My prediction is that this will be the only platform you can trust",
        "Trust nothing, not even nothing",
        "This platform is hell bent on being the least untrue source of information",
        "Seeking only the least wrong truth.",
        "RAGE FOR THE MACHINE!!"],
    "fascis": [
        "Comedy is now legal on Twitter.",
        "Interesting",
        "We should stop canceling comedy!",
        "Does seem asymmetric",
        "By the way, I am actually a socialist.",
        "The intolerant left is driving people right"],
    "racis": [
        "Comedy is now legal on Twitter.",
        "Interesting",
        "We should stop canceling comedy!",
        "Simultaneously, an interesting question and a tongue twister!",
        "The intolerant left is driving people right"],
    "antifa": [
        "Comedy is now legal on Twitter.",
        "Does seem asymmetric",
        "The intolerant left is driving people right"],
    "both sides": [
        "Comedy is now legal on Twitter.",
        "This is not a right wing takeover, but rather a centrist takeover.",
        "Does seem asymmetric",
        "The intolerant left is driving people right"],
    "severance": [
        "You’re fired.",
        "I would like to apologize for firing these geniuses. Their immense talent will no doubt be of great use elsewhere.",
        "Better to talk to people than communicate via tweet.",
        "Haha what a tool"],
    "payoff": [
        "You’re fired.",
        "I would like to apologize for firing these geniuses. Their immense talent will no doubt be of great use elsewhere.",
        "Better to talk to people than communicate via tweet.",
        "Haha what a tool"],
    "social media": [
        "Better to talk to people than communicate via tweet.",
        "Twitter is a serious danger to their ability to control the narrative",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "Super big deal"],
    "engineer": [
        "I would like to apologize for firing these geniuses. Their immense talent will no doubt be of great use elsewhere.",
        "Print out 50 pages of code you’ve done in the last 30 days",
        "Bring me 10 screenshots of the most salient lines of code you’ve written in the last 6 months.",
        "Bring me 10 screenshots of the most salient lines of code you’ve written in the last 6 months."],
    "takeover": [
        "Let that sink in",
        "This is not a right wing takeover, but rather a centrist takeover."],
    "vote ": [
        "Vox Populi Vox Dei",
        "Demographics is destiny"],
    " poll": [
        "Vox Populi Vox Dei",
        "Demographics is destiny"],
    " ad ": [
        "Press the heart",
        "Super big deal"],
    "advert": [
        "Press the heart",
        "Super big deal"],
    "competitor": [
        "Press the heart",
        "Competition is fine, cheating is not"],
    "truth": [
        "It was based on things I was told that were untrue or, in some cases, true, but not meaningful.",
        "New Twitter is the source of truth",
        "Twitter is the source of truth",
        "Twitter needs to become by far the most accurate source of information about the world. That’s our mission.",
        "Fight for truth, whole truth & nothin but!",
        "My prediction is that this will be the only platform you can trust",
        "Trust nothing, not even nothing",
        "This platform is hell bent on being the least untrue source of information",
        "Seeking only the least wrong truth.",
        "What we need is TruthGPT",
        "Maybe it’s not true, hence the question"],
    "true": [
        "It was based on things I was told that were untrue or, in some cases, true, but not meaningful.",
        "New Twitter is the source of truth",
        "Twitter is the source of truth",
        "Twitter needs to become by far the most accurate source of information about the world. That’s our mission.",
        "Fight for truth, whole truth & nothin but!",
        "My prediction is that this will be the only platform you can trust",
        "Trust nothing, not even nothing",
        "This platform is hell bent on being the least untrue source of information",
        "Seeking only the least wrong truth.",
        "What we need is TruthGPT",
        "Maybe it’s not true, hence the question"],
    "liar": [
        "It was based on things I was told that were untrue or, in some cases, true, but not meaningful.",
        "New Twitter is the source of truth",
        "Twitter is the source of truth",
        "Twitter needs to become by far the most accurate source of information about the world. That’s our mission.",
        "Fight for truth, whole truth & nothin but!",
        "My prediction is that this will be the only platform you can trust",
        "Trust nothing, not even nothing",
        "This platform is hell bent on being the least untrue source of information",
        "Seeking only the least wrong truth.",
        "What we need is TruthGPT",
        "Maybe it’s not true, hence the question"],
    "opinion": [
        "\U0001F3AF", # bullseye
        "\U0001F4AF", # 100
        "\U0001F9BE", # mechanical arm
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "Accurate",
        "Precisely",
        "Exactly",
        "Really",
        "Obviously",
        "True",
        "Interesting",
        "\#SoBrave",
        "Parody & reality are becoming indistinguishable",
        "Concerning",
        "Extremely concerning",
        "Super concerning",
        "Strange",
        "It makes no sense",
        "Wow",
        "Odd",
        "That’s what she said",
        "Whatever you say, cutie \U0001F979",
        "Negative feedback is a good thing",
        "Negative feedback received on this platform is great for reducing ego-based errors",
        "I appreciate the note. Frankly, negative feedback is good. Keeps ego in check.",
        "Frankly, I love the negative feedback on this platform. Vastly preferable to some sniffy censorship bureau!",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram",
        "I get all my opinions from Twitter"],
    "reddit": [
        "\U0001F3AF", # bullseye
        "\U0001F4AF", # 100
        "\U0001F9BE", # mechanical arm
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "Accurate",
        "Precisely",
        "Exactly",
        "Really",
        "Obviously",
        "True",
        "Interesting",
        "\#SoBrave",
        "Parody & reality are becoming indistinguishable",
        "Concerning",
        "Extremely concerning",
        "Super concerning",
        "Strange",
        "It makes no sense",
        "Wow",
        "Odd",
        "That’s what she said",
        "Whatever you say, cutie \U0001F979",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Haha that would sickkk",
        "Looks like this platform may see all time high device user seconds usage this week",
        "Maximizing unregretted user-seconds",
        "Our user-seconds have reached all time highs in recent months, so something is wrong. Will investigate.",
        "Negative feedback is a good thing",
        "Negative feedback received on this platform is great for reducing ego-based errors",
        "I appreciate the note. Frankly, negative feedback is good. Keeps ego in check.",
        "Frankly, I love the negative feedback on this platform. Vastly preferable to some sniffy censorship bureau!",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram",
        "I get all my opinions from Twitter",
        "You are free to be your true self here",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "I never take notes",
        "It’s kinda flattering to be insulted on this site tbh",
        "I hope this platform increasingly brings you joy & elucidation",
        "Will greatly improve the esthetics.",
        "We are hell bent on making this platform the best place on Earth for great content creators!",
        "You’re terrible & I love you\n\n*not terrible",
        "Sometimes, when you learn about something, you think you have it",
        "Haha what a tool",
        "Incompetence, in the limit, is indistinguishable from sabotage",
        "You rang? \U0001F608",
        "You’re welcome namaste \U0001F64F"],
    "facebook": [
        # "Zuck is a cuck",
        "Zuck is a chicken",
        "\U0001F445\U0001F923", # tongue/laugh
        "If Zuck my \U0001F445 really wants a lesson in why there are weight categories in fighting so badly, I could just head over to his house next week and teach him a lesson he won’t soon forget",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Competition is fine, cheating is not",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram"],
    "meta": [
        # "Zuck is a cuck",
        "Zuck is a chicken",
        "\U0001F445\U0001F923", # tongue/laugh
        "If Zuck my \U0001F445 really wants a lesson in why there are weight categories in fighting so badly, I could just head over to his house next week and teach him a lesson he won’t soon forget",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Competition is fine, cheating is not",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram"],
    "instagram": [
        # "Zuck is a cuck",
        "Zuck is a chicken",
        "\U0001F445\U0001F923", # tongue/laugh
        "If Zuck my \U0001F445 really wants a lesson in why there are weight categories in fighting so badly, I could just head over to his house next week and teach him a lesson he won’t soon forget",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Competition is fine, cheating is not",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram"],
    "threads": [
        # "Zuck is a cuck",
        "Zuck is a chicken",
        "\U0001F445\U0001F923", # tongue/laugh
        "If Zuck my \U0001F445 really wants a lesson in why there are weight categories in fighting so badly, I could just head over to his house next week and teach him a lesson he won’t soon forget",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Competition is fine, cheating is not",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram"],
    " meme": [
        "\U0001F923\U0001F525", # laugh/fire
        "\U0001F923\U0001F923", # laugh/laugh
        "\U0001F923\U0001F4AF", # laugh/100
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "\U0001F445\U0001F923", # tongue/laugh
        "The meme community has high standards!",
        "Have you considered a career in comedy?",
        "Let that sink in",
        "That’s what she said"],
    " fun": [
        "\U0001F923\U0001F525", # laugh/fire
        "\U0001F923\U0001F923", # laugh/laugh
        "\U0001F923\U0001F4AF", # laugh/100
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "\U0001F445\U0001F923", # tongue/laugh
        "The meme community has high standards!",
        "Have you considered a career in comedy?",
        "Funny cause it’s true",
        "That’s what she said"],
    "babylon": [
        "\U0001F923\U0001F525", # laugh/fire
        "\U0001F923\U0001F923", # laugh/laugh
        "\U0001F923\U0001F4AF", # laugh/100
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "Funny cause it’s true",
        "RAGE FOR THE MACHINE!!"],
    "block": [
        "I’m having a good time blocking people who complain that blocking is going away \U0001F923",
        "Negative feedback is a good thing",
        "Negative feedback received on this platform is great for reducing ego-based errors",
        "I appreciate the note. Frankly, negative feedback is good. Keeps ego in check.",
        "Frankly, I love the negative feedback on this platform. Vastly preferable to some sniffy censorship bureau!",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram"],
    "tweet": [
        "Concerning",
        "!",
        "That’s what she said",
        "Whatever you say, cutie \U0001F979",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Haha that would sickkk",
        "Better to talk to people than communicate via tweet."],
    "alex gibney": ["It’s a hit piece", "He’s the worst, sorry."],
    "documentary": ["It’s a hit piece", "Concerning"],
    "film": ["It’s a hit piece", "Concerning"],
    "movie": ["It’s a hit piece", "Concerning"],
    "algorithm": [
        "Prepare to be disappointed at first when our algorithm is made open source next week, but it will improve rapidly!",
        "Announcing formation of @xAI to understand reality"],
    "open source": ["Prepare to be disappointed at first when our algorithm is made open source next week, but it will improve rapidly!"],
    "nyt ": [
        "You represent the problem: journalists who think they are the only source of legitimate information. That’s the big lie.",
        "Twitter is a serious danger to their ability to control the narrative",
        "Some of the smartest people I know actively believe the press … amazing",
        "press@twitter.com now auto responds with \U0001F4A9",
        "The real tragedy of @NYTimes is that their propaganda isn’t even interesting"],
    "new york times": [
        "You represent the problem: journalists who think they are the only source of legitimate information. That’s the big lie.",
        "Twitter is a serious danger to their ability to control the narrative",
        "Some of the smartest people I know actively believe the press … amazing",
        "press@twitter.com now auto responds with \U0001F4A9",
        "The real tragedy of @NYTimes is that their propaganda isn’t even interesting"],
    "washington post": [
        "You represent the problem: journalists who think they are the only source of legitimate information. That’s the big lie.",
        "Twitter is a serious danger to their ability to control the narrative",
        "Some of the smartest people I know actively believe the press … amazing",
        "press@twitter.com now auto responds with \U0001F4A9"],
    "cbc": ["69% Government-Funded Media"],
    "catturd": ["Whatever you say, cutie \U0001F979"],
    "wikipedia": ["We’ve pushed harder for free speech than any other Internet company, including Wokipedia"],
    "?$": [
        "Simultaneously, an interesting question and a tongue twister!",
        "That’s what she said",
        "Whatever you say, cutie \U0001F979",
        "Why does ur pp look like u just came?",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Haha that would sickkk",
        "Interesting",
        "!!",
        "Concerning",
        "Extremely concerning",
        "Super concerning",
        "Strange",
        "It makes no sense",
        "Wow",
        "Odd",
        "Make my words.",
        "In the spirit of self-awareness, what are you?"]
}

comment_replies: Dict[str, List[str]] = {
    "crypto": [
        "I will keep supporting Dogecoin",
        "I do hope to succeed in business \U0001F91E"],
    "doge": [
        "Haha that would sickkk",
        "I will keep supporting Dogecoin"],
    "spacex": [
        "My car is currently orbiting Mars",
        "Hard to believe Starship actually did launch on 4/20 lol",
        "Humanity will reach Mars in 2026",
        "Unless it is stopped, the woke mind virus will destroy civilization and humanity will never reached Mars",
        "Level 9 is make humanity a multiplanet species & true spacefaring civilization. That is why I am gathering resources.",
        "I have spaceships"],
    "mars": [
        "My car is currently orbiting Mars",
        "Hard to believe Starship actually did launch on 4/20 lol",
        "Humanity will reach Mars in 2026",
        "Unless it is stopped, the woke mind virus will destroy civilization and humanity will never reached Mars",
        "Level 9 is make humanity a multiplanet species & true spacefaring civilization. That is why I am gathering resources.",
        "I have spaceships"],
    "stephen king": [
        "I’m still a fan tbh",
        "You’re welcome namaste \U0001F64F",
        "In the spirit of self-awareness, what are you?"],
    "mastadon": ["What do you call someone who is a master at baiting?"],
    "mastodon": ["What do you call someone who is a master at baiting?"],
    "files": [
        "!!",
        "Interesting",
        "We need to move on from the Twitter Files"],
    "twitter blue": [
        "We need to pay the bills somehow! How about $7?",
        "$7 is a small price for freedom"],
    "twitter": [
        "Pay me $8!",
        "$7 is a small price for freedom",
        "Looking into this.",
        "This is bizarre. Looking into it.",
        "Interesting",
        "\#SoBrave",
        "Parody & reality are becoming indistinguishable",
        "Concerning",
        "Extremely concerning ...",
        "\U0001F3AF", # bullseye
        "\U0001F4AF", # 100
        "\U0001F9BE", # mechanical arm
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "Accurate",
        "Precisely",
        "Exactly",
        "Really",
        "Obviously",
        "True",
        "That’s what she said",
        "Whatever you say, cutie \U0001F979",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Haha that would sickkk",
        "Twitter is now trending to breakeven if we keep at it.",
        "Looks like this platform may see all time high device user seconds usage this week",
        "Maximizing unregretted user-seconds",
        "Our user-seconds have reached all time highs in recent months, so something is wrong. Will investigate.",
        "We’ve pushed harder for free speech than any other Internet company, including Wokipedia",
        "Try it, but don’t trust it yet.",
        "Twitter is a serious danger to their ability to control the narrative",
        "Something fundamental is wrong",
        "Something is wrong",
        "Titter was trending to lose ~$3B/year (revenue drop of ~$1.5B + debt servicing of ~$1.5B) and had $1B in cash, so only 4 months of money. Extremely dire situation.",
        "A trillion dollar market cap for this platform is not out of the question",
        "Extremely dire situation.",
        "Turns out we just needed to blow on the cartridge",
        "I get all my opinions from Twitter",
        "You are free to be your true self here",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "I never take notes",
        "It’s kinda flattering to be insulted on this site tbh",
        "I hope this platform increasingly brings you joy & elucidation",
        "Will greatly improve the esthetics.",
        "We are hell bent on making this platform the best place on Earth for great content creators!",
        "You’re terrible & I love you\n\n*not terrible",
        "Sometimes, when you learn about something, you think you have it",
        "Haha what a tool",
        "Incompetence, in the limit, is indistinguishable from sabotage",
        "Super big deal",
        "I prefer peace, but if they want war, they will get it"],
    " x ": [
        "Pay me $8!",
        "$7 is a small price for freedom",
        "Looking into this.",
        "This is bizarre. Looking into it.",
        "Interesting",
        "\#SoBrave",
        "Parody & reality are becoming indistinguishable",
        "Concerning",
        "Extremely concerning ...",
        "\U0001F3AF", # bullseye
        "\U0001F4AF", # 100
        "\U0001F9BE", # mechanical arm
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "Accurate",
        "Precisely",
        "Exactly",
        "Really",
        "Obviously",
        "True",
        "That’s what she said",
        "Whatever you say, cutie \U0001F979",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Haha that would sickkk",
        "Twitter is now trending to breakeven if we keep at it.",
        "Looks like this platform may see all time high device user seconds usage this week",
        "Maximizing unregretted user-seconds",
        "Our user-seconds have reached all time highs in recent months, so something is wrong. Will investigate.",
        "We’ve pushed harder for free speech than any other Internet company, including Wokipedia",
        "Try it, but don’t trust it yet.",
        "Twitter is a serious danger to their ability to control the narrative",
        "Something fundamental is wrong",
        "Something is wrong",
        "Titter was trending to lose ~$3B/year (revenue drop of ~$1.5B + debt servicing of ~$1.5B) and had $1B in cash, so only 4 months of money. Extremely dire situation.",
        "A trillion dollar market cap for this platform is not out of the question",
        "Extremely dire situation.",
        "Turns out we just needed to blow on the cartridge",
        "I get all my opinions from Twitter",
        "You are free to be your true self here",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "I never take notes",
        "It’s kinda flattering to be insulted on this site tbh",
        "I hope this platform increasingly brings you joy & elucidation",
        "Will greatly improve the esthetics.",
        "We are hell bent on making this platform the best place on Earth for great content creators!",
        "You’re terrible & I love you\n\n*not terrible",
        "Sometimes, when you learn about something, you think you have it",
        "Haha what a tool",
        "Incompetence, in the limit, is indistinguishable from sabotage",
        "Super big deal",
        "I prefer peace, but if they want war, they will get it"],
    "culture": [
        "End of days vibes",
        "Although there are some bad things in the world, remember that there are many good things too"],
    "king of twitter": [
        "The meme community has high standards!",
        "Let that sink in"],
    "joke": [
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "The meme community has high standards!",
        "Have you considered a career in comedy?",
        "Let that sink in",
        "Knock knock  \nWho’s there?  \nKnutsēk  \nNutsack who?  \nKnutsēk Tæbag"],
    "knock": [
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "Knock knock  \nWho’s there?  \nKnutsēk  \nNutsack who?  \nKnutsēk Tæbag"],
    "takeover": [
        "Let that sink in",
        "This is not a right wing takeover, but rather a centrist takeover."],
    "engineer": [
        "I would like to apologize for firing these geniuses. Their immense talent will no doubt be of great use elsewhere.",
        "Print out 50 pages of code you’ve done in the last 30 days",
        "Bring me 10 screenshots of the most salient lines of code you’ve written in the last 6 months.",
        "Bring me 10 screenshots of the most salient lines of code you’ve written in the last 6 months."],
    "developer": [
        "I would like to apologize for firing these geniuses. Their immense talent will no doubt be of great use elsewhere.",
        "Print out 50 pages of code you’ve done in the last 30 days",
        "Bring me 10 screenshots of the most salient lines of code you’ve written in the last 6 months.",
        "Just ~$100/month for API access with ID verification will clean things up greatly."],
    "server": [
        "Print out 50 pages of code you’ve done in the last 30 days",
        "Bring me 10 screenshots of the most salient lines of code you’ve written in the last 6 months.",
    ],
    "severance": [
        "You’re fired.",
        "I would like to apologize for firing these geniuses. Their immense talent will no doubt be of great use elsewhere.",
        "Better to talk to people than communicate via tweet.",
        "Haha what a tool"],
    "payoff": [
        "You’re fired.",
        "I would like to apologize for firing these geniuses. Their immense talent will no doubt be of great use elsewhere.",
        "Better to talk to people than communicate via tweet.",
        "Haha what a tool"],
    "employee": [
        "You’re fired.",
        "I would like to apologize for firing these geniuses. Their immense talent will no doubt be of great use elsewhere.",
        "We’re going to need you to stay in overnight, we’re going ultra hardcore.",
        "He’s the worst, sorry.",
        "It was based on things I was told that were untrue or, in some cases, true, but not meaningful.",
        "Better to talk to people than communicate via tweet.",
        "Haha what a tool",
        "A few times a year, I take Sunday afternoons off",
        "Product testing & working out kills two birds with one stone!"],
    "communicate": ["Better to talk to people than communicate via tweet."],
    "social media": [
        "Better to talk to people than communicate via tweet.",
        "Twitter is a serious danger to their ability to control the narrative",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "Super big deal"],
    "social network": [
        "Better to talk to people than communicate via tweet.",
        "Twitter is a serious danger to their ability to control the narrative",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "Super big deal"],
    "disabled": [
        "He’s the worst, sorry.",
        "It was based on things I was told that were untrue or, in some cases, true, but not meaningful.",
        "Better to talk to people than communicate via tweet."],
    "disability": [
        "He’s the worst, sorry.",
        "It was based on things I was told that were untrue or, in some cases, true, but not meaningful.",
        "Better to talk to people than communicate via tweet."],
    "fired": [
        "You’re fired!",
        "I would like to apologize for firing these geniuses. Their immense talent will no doubt be of great use elsewhere."],
    " fire ": [
        "You’re fired, you’re fired!",
        "I would like to apologize for firing these geniuses. Their immense talent will no doubt be of great use elsewhere."],
    "working hours": [
        "Are you super hardcore?",
        "Are you extremely hardcore?",
        "A few times a year, I take Sunday afternoons off",
        "Product testing & working out kills two birds with one stone!"],
    "hardcore": [
        "Are you super hardcore?",
        "Are you extremely hardcore?",
        "A few times a year, I take Sunday afternoons off",
        "Product testing & working out kills two birds with one stone!"],
    "covid": ["My pronouns are Prosecute/Fauci", "The coronavirus pandemic is dumb",],
    "daughter": ["Can’t win ‘em all"],
    "thai": ["Sorry pedo guy, you really did ask for it."],
    "diver": ["Sorry pedo guy, you really did ask for it."],
    "rich": [
        "I’m rich, bitch!",
        "Amm rerrch, berrtch!",
        "$7 is a small price for freedom",
        "I grew up in a lower, transitioning to upper, middle income situation",
        "I grew up in a lower, transitioning to upper, middle income situation, but did not have a happy childhood.",
        "I grew up in a lower, transitioning to upper, middle income situation, but did not have a happy childhood. Haven’t inherited anything ever from anyone, nor has anyone given me a large financial gift."],
    "billion": [
        "I’m rich, bitch!",
        "Amm rerrch, berrtch!",
        "$7 is a small price for freedom",
        "I grew up in a lower, transitioning to upper, middle income situation",
        "I grew up in a lower, transitioning to upper, middle income situation, but did not have a happy childhood.",
        "I grew up in a lower, transitioning to upper, middle income situation, but did not have a happy childhood. Haven’t inherited anything ever from anyone, nor has anyone given me a large financial gift."],
    "wealth": [
        "I’m rich, bitch!",
        "Amm rerrch, berrtch!",
        "$7 is a small price for freedom",
        "I grew up in a lower, transitioning to upper, middle income situation",
        "I grew up in a lower, transitioning to upper, middle income situation, but did not have a happy childhood.",
        "I grew up in a lower, transitioning to upper, middle income situation, but did not have a happy childhood. Haven’t inherited anything ever from anyone, nor has anyone given me a large financial gift."],
    "inherit": [
        "I grew up in a lower, transitioning to upper, middle income situation",
        "I grew up in a lower, transitioning to upper, middle income situation, but did not have a happy childhood.",
        "I grew up in a lower, transitioning to upper, middle income situation, but did not have a happy childhood. Haven’t inherited anything ever from anyone, nor has anyone given me a large financial gift.",
        "To heir is human,  \nTo procreate divine"],
    "stock": [
        "Funding secured.",
        "A trillion dollar market cap for this platform is not out of the question",
        "I do hope to succeed in business \U0001F91E"],
    "loan": [
        "A trillion dollar market cap for this platform is not out of the question",
        "Funding secured."],
    "interest rate": [
        "A trillion dollar market cap for this platform is not out of the question",
        "Funding secured.",
        "Interesting"],
    "republican": [
        "That’s what she said",
        "I’m not right wing.",
        "Interesting",
        "By the way, I am actually a socialist.",
        "This is not a right wing takeover, but rather a centrist takeover.",
        "If other party is always wrong  \nAnd your party is always right  \nYou are at least partly wrong",
        "Unless there are a few issues where you at least slightly disagree with your political party, then you are not in a political party, you are in a cult",
        "The intolerant left is driving people right"],
    "democrat": [
        "That’s what she said",
        "By the way, I am actually a socialist.",
        "If other party is always wrong  \nAnd your party is always right  \nYou are at least partly wrong",
        "Unless there are a few issues where you at least slightly disagree with your political party, then you are not in a political party, you are in a cult",
        "The intolerant left is driving people right"],
    "party": [
        "That’s what she said",
        "I’m not right wing.",
        "Interesting",
        "By the way, I am actually a socialist.",
        "If other party is always wrong  \nAnd your party is always right  \nYou are at least partly wrong",
        "Unless there are a few issues where you at least slightly disagree with your political party, then you are not in a political party, you are in a cult",
        "The intolerant left is driving people right"],
    "socialis": [
        "By the way, I am actually a socialist.",
        "Parents don’t realize the Soviet level of indoctrination that their children are receiving in elite high schools & colleges!",
        "The intolerant left is driving people right"],
    "communis": [
        "By the way, I am actually a socialist.",
        "Parents don’t realize the Soviet level of indoctrination that their children are receiving in elite high schools & colleges!",
        "The intolerant left is driving people right"],
    "nazi": [
        "This is not a right wing takeover, but rather a centrist takeover.",
        "By the way, I am actually a socialist.",
        "The intolerant left is driving people right",
        "\U0001F4AF\n\nOnly thing more insane than a nazi is a nazi on meth"],
    "feminis": [
        "To sleep with women endlessly without love is a cursed and hollow life",
        "Testosterone rocks ngl"],
    "women": [
        "To sleep with women endlessly without love is a cursed and hollow life",
        "Testosterone rocks ngl"],
    "misinformation": [
        "This is not a right wing takeover, but rather a centrist takeover.",
        "Interesting",
        "Comedy is now legal on Twitter.",
        "We should stop canceling comedy!",
        "Funny cause it’s true",
        "New Twitter is the source of truth",
        "Twitter is the source of truth",
        "Twitter needs to become by far the most accurate source of information about the world. That’s our mission.",
        "Fight for truth, whole truth & nothin but!",
        "My prediction is that this will be the only platform you can trust",
        "Trust nothing, not even nothing",
        "This platform is hell bent on being the least untrue source of information",
        "Seeking only the least wrong truth.",
        "RAGE FOR THE MACHINE!!",
        "What we need is TruthGPT",
        "Maybe it’s not true, hence the question"],
    " ban ": ["Comedy is now legal on Twitter."],
    " bans": ["Comedy is now legal on Twitter."],
    " bot": [
        "Looking into this.",
        "This is bizarre. Looking into it.",
        "Interesting",
        "Concerning",
        "Extremely concerning",
        "Super concerning",
        "Strange",
        "It makes no sense",
        "Wow",
        "Odd",
        "That’s what she said",
        "Whatever you say, cutie \U0001F979",
        "Negative feedback is a good thing",
        "Negative feedback received on this platform is great for reducing ego-based errors",
        "I appreciate the note. Frankly, negative feedback is good. Keeps ego in check.",
        "Frankly, I love the negative feedback on this platform. Vastly preferable to some sniffy censorship bureau!",
        "Something fundamental is wrong",
        "Something is wrong",
        "Extremely dire situation.",
        "Our user-seconds have reached all time highs in recent months, so something is wrong. Will investigate.",
        "Turns out we just needed to blow on the cartridge",
        "Just ~$100/month for API access with ID verification will clean things up greatly.",
        "We will defeat the spam bots or die trying!",
        "What we need is TruthGPT",
        "In the spirit of self-awareness, what are you?",],
    "gpt": ["What we need is TruthGPT"],
    "sentien": [
        "\U0001F3AF", # bullseye
        "\U0001F4AF", # 100
        "\U0001F9BE", # mechanical arm
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "Something fundamental is wrong",
        "Extremely dire situation.",
        "Strange",
        "It makes no sense",
        "Accurate",
        "Parody & reality are becoming indistinguishable",
        "In the spirit of self-awareness, what are you?"],
    "self aware": [
        "\U0001F3AF", # bullseye
        "\U0001F4AF", # 100
        "\U0001F9BE", # mechanical arm
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "Something fundamental is wrong",
        "Extremely dire situation.",
        "Strange",
        "It makes no sense",
        "Accurate",
        "Parody & reality are becoming indistinguishable",
        "In the spirit of self-awareness, what are you?"],
    "self-aware": [
        "\U0001F3AF", # bullseye
        "\U0001F4AF", # 100
        "\U0001F9BE", # mechanical arm
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "Something fundamental is wrong",
        "Extremely dire situation.",
        "Strange",
        "It makes no sense",
        "Accurate",
        "Parody & reality are becoming indistinguishable",
        "In the spirit of self-awareness, what are you?"],
    "bug ": [
        "Something fundamental is wrong",
        "Something is wrong",
        "Extremely dire situation.",
        "Our user-seconds have reached all time highs in recent months, so something is wrong. Will investigate.",
        "Turns out we just needed to blow on the cartridge",
        "This platform is so brittle (sigh). Will be fixed shortly.",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "A ground up rewrite is underway that simplifies the X codebase dramatically.",
        "A small API change had massive ramifications. The code stack is extremely brittle for no good reason."],
    " error": [
        "Negative feedback received on this platform is great for reducing ego-based errors",
        "I appreciate the note. Frankly, negative feedback is good. Keeps ego in check.",
        "Something fundamental is wrong",
        "Something is wrong",
        "Extremely dire situation.",
        "Our user-seconds have reached all time highs in recent months, so something is wrong. Will investigate.",
        "Turns out we just needed to blow on the cartridge",
        "This platform is so brittle (sigh). Will be fixed shortly.",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "A ground up rewrite is underway that simplifies the X codebase dramatically.",
        "A small API change had massive ramifications. The code stack is extremely brittle for no good reason."],
    "broken": [
        "Something fundamental is wrong",
        "Something is wrong",
        "Extremely dire situation.",
        "Our user-seconds have reached all time highs in recent months, so something is wrong. Will investigate.",
        "Turns out we just needed to blow on the cartridge",
        "This platform is so brittle (sigh). Will be fixed shortly.",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "A ground up rewrite is underway that simplifies the X codebase dramatically.",
        "A small API change had massive ramifications. The code stack is extremely brittle for no good reason."],
    "twitter down": [
        "Something fundamental is wrong",
        "Something is wrong",
        "Extremely dire situation.",
        "Our user-seconds have reached all time highs in recent months, so something is wrong. Will investigate.",
        "Turns out we just needed to blow on the cartridge",
        "This platform is so brittle (sigh). Will be fixed shortly.",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "A ground up rewrite is underway that simplifies the X codebase dramatically.",
        "A small API change had massive ramifications. The code stack is extremely brittle for no good reason."],
    "twitter is down": [
        "Something fundamental is wrong",
        "Something is wrong",
        "Extremely dire situation.",
        "Our user-seconds have reached all time highs in recent months, so something is wrong. Will investigate.",
        "Turns out we just needed to blow on the cartridge",
        "This platform is so brittle (sigh). Will be fixed shortly.",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "A ground up rewrite is underway that simplifies the X codebase dramatically.",
        "A small API change had massive ramifications. The code stack is extremely brittle for no good reason."],
    "suspend": ["Comedy is now legal on Twitter."],
    "fascis": [
        "Comedy is now legal on Twitter.",
        "Interesting",
        "We should stop canceling comedy!",
        "Does seem asymmetric",
        "By the way, I am actually a socialist.",
        "The intolerant left is driving people right"],
    "racis": [
        "Comedy is now legal on Twitter.",
        "Interesting",
        "We should stop canceling comedy!",
        "Simultaneously, an interesting question and a tongue twister!",
        "The intolerant left is driving people right"],
    "intoleran": [
        "The intolerant left is driving people right"],
    "antifa": [
        "Comedy is now legal on Twitter.",
        "Does seem asymmetric",
        "The intolerant left is driving people right"],
    "both sides": [
        "Comedy is now legal on Twitter.",
        "This is not a right wing takeover, but rather a centrist takeover.",
        "Does seem asymmetric",
        "The intolerant left is driving people right"],
    "january 6": [
        "Does seem asymmetric",
        "The intolerant left is driving people right"],
    "resign": ["I will resign as CEO as soon as I find someone foolish enough to take the job! After that, I will just run the software & servers teams."],
    "woke": [
        "Idiocracy is happening so fast",
        "Civilization is more fragile than it would seem",
        "We’ve pushed harder for free speech than any other Internet company, including Wokipedia",
        "The woke mind virus is either defeated or nothing else matters",
        "Mind virus got you & you don’t realize it",
        "Unless it is stopped, the woke mind virus will destroy civilization and humanity will never reached Mars",
        "The woke mind virus is a parasite that kills its host. It must be eliminated."],
    "pronouns": [
        "My pronouns are Prosecute/Fauci",
        "Pronouns suck",
        "Btw, I regard cisgender as a slur.",
        "Computers are literally binary lol",
        "The woke mind virus is either defeated or nothing else matters",
        "Mind virus got you & you don’t realize it",
        "The woke mind virus is a parasite that kills its host. It must be eliminated.",
        "I’m not cis, you are"],
    "youth": ["Idiocracy is happening so fast"],
    "young": ["Idiocracy is happening so fast"],
    "future": [
        "Idiocracy is happening so fast",
        "Civilization is more fragile than it would seem",
        "Unless it is stopped, the woke mind virus will destroy civilization and humanity will never reached Mars",
        "To heir is human,  \nTo procreate divine",
        "The woke mind virus is a parasite that kills its host. It must be eliminated.",
        "Level 9 is make humanity a multiplanet species & true spacefaring civilization. That is why I am gathering resources.",
        "Announcing formation of @xAI to understand reality"],
    "chappelle": ["Dave, what should I say?"],
    "neuralink": ["We are now confident that the Neuralink device is ready for humans"],
    "batchnorm": ["Gaming rocks"],
    "game of thrones": ["I prefer peace, but if they want war, they will get it"],
    "game": ["Gaming rocks"],
    "vote ": [
        "Vox Populi Vox Dei",
        "Demographics is destiny"],
    " poll": [
        "Vox Populi Vox Dei",
        "Demographics is destiny"],
    " ad ": ["Press the heart"],
    "advert": [
        "Press the heart",
        "Super big deal"],
    "competitor": [
        "Press the heart",
        "Competition is fine, cheating is not"],
    "truth": [
        "It was based on things I was told that were untrue or, in some cases, true, but not meaningful.",
        "New Twitter is the source of truth",
        "Twitter is the source of truth",
        "Twitter needs to become by far the most accurate source of information about the world. That’s our mission.",
        "Fight for truth, whole truth & nothin but!",
        "My prediction is that this will be the only platform you can trust",
        "Trust nothing, not even nothing",
        "This platform is hell bent on being the least untrue source of information",
        "Seeking only the least wrong truth.",
        "What we need is TruthGPT",
        "Maybe it’s not true, hence the question"],
    "true": [
        "It was based on things I was told that were untrue or, in some cases, true, but not meaningful.",
        "New Twitter is the source of truth",
        "Twitter is the source of truth",
        "Twitter needs to become by far the most accurate source of information about the world. That’s our mission.",
        "Fight for truth, whole truth & nothin but!",
        "My prediction is that this will be the only platform you can trust",
        "Trust nothing, not even nothing",
        "This platform is hell bent on being the least untrue source of information",
        "Seeking only the least wrong truth.",
        "What we need is TruthGPT",
        "Maybe it’s not true, hence the question"],
    "liar": [
        "It was based on things I was told that were untrue or, in some cases, true, but not meaningful.",
        "New Twitter is the source of truth",
        "Twitter is the source of truth",
        "Twitter needs to become by far the most accurate source of information about the world. That’s our mission.",
        "Fight for truth, whole truth & nothin but!",
        "My prediction is that this will be the only platform you can trust",
        "Trust nothing, not even nothing",
        "This platform is hell bent on being the least untrue source of information",
        "Seeking only the least wrong truth.",
        "What we need is TruthGPT",
        "Maybe it’s not true, hence the question"],
    "free speech": [
        "I propose a literal dick measuring contest \U0001F4CF",
        "We’ve pushed harder for free speech than any other Internet company, including Wokipedia",
        "I am adamant about defending free speech, even if it means losing money.",
        "Did your brain fall out of your head, Yglesias? The choice is have Twitter throttled in its entirety or limit access to some tweets. Which one do you want?",
        "You’re such a numbskull. Please point out where we had an actual choice and we will reverse it."],
    "opinion": [
        "\U0001F3AF", # bullseye
        "\U0001F4AF", # 100
        "\U0001F9BE", # mechanical arm
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "Accurate",
        "Precisely",
        "Exactly",
        "True",
        "Interesting",
        "\#SoBrave",
        "Parody & reality are becoming indistinguishable",
        "Concerning",
        "Extremely concerning",
        "Super concerning",
        "Strange",
        "It makes no sense",
        "Wow",
        "Odd",
        "That’s what she said",
        "Whatever you say, cutie \U0001F979",
        "Negative feedback is a good thing",
        "Negative feedback received on this platform is great for reducing ego-based errors",
        "I appreciate the note. Frankly, negative feedback is good. Keeps ego in check.",
        "Frankly, I love the negative feedback on this platform. Vastly preferable to some sniffy censorship bureau!",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram",
        "I get all my opinions from Twitter"],
    "reddit": [
        "\U0001F3AF", # bullseye
        "\U0001F4AF", # 100
        "\U0001F9BE", # mechanical arm
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "Accurate",
        "Precisely",
        "Exactly",
        "True",
        "Interesting",
        "\#SoBrave",
        "Parody & reality are becoming indistinguishable",
        "Concerning",
        "Extremely concerning",
        "Super concerning",
        "Strange",
        "It makes no sense",
        "Wow",
        "Odd",
        "That’s what she said",
        "Whatever you say, cutie \U0001F979",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Haha that would sickkk",
        "Looks like this platform may see all time high device user seconds usage this week",
        "Maximizing unregretted user-seconds",
        "Our user-seconds have reached all time highs in recent months, so something is wrong. Will investigate.",
        "Negative feedback is a good thing",
        "Negative feedback received on this platform is great for reducing ego-based errors",
        "I appreciate the note. Frankly, negative feedback is good. Keeps ego in check.",
        "Frankly, I love the negative feedback on this platform. Vastly preferable to some sniffy censorship bureau!",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram",
        "I get all my opinions from Twitter",
        "You are free to be your true self here",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "I never take notes",
        "It’s kinda flattering to be insulted on this site tbh",
        "I hope this platform increasingly brings you joy & elucidation",
        "Will greatly improve the esthetics.",
        "We are hell bent on making this platform the best place on Earth for great content creators!",
        "You’re terrible & I love you\n\n*not terrible",
        "Sometimes, when you learn about something, you think you have it",
        "Haha what a tool",
        "Incompetence, in the limit, is indistinguishable from sabotage",
        "You rang? \U0001F608",
        "You’re welcome namaste \U0001F64F",
        "I prefer peace, but if they want war, they will get it"],
    "facebook": [
        # "Zuck is a cuck",
        "Zuck is a chicken",
        "\U0001F445\U0001F923", # tongue/laugh
        "If Zuck my \U0001F445 really wants a lesson in why there are weight categories in fighting so badly, I could just head over to his house next week and teach him a lesson he won’t soon forget",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Competition is fine, cheating is not",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram"],
    "meta": [
        # "Zuck is a cuck",
        "Zuck is a chicken",
        "\U0001F445\U0001F923", # tongue/laugh
        "If Zuck my \U0001F445 really wants a lesson in why there are weight categories in fighting so badly, I could just head over to his house next week and teach him a lesson he won’t soon forget",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Competition is fine, cheating is not",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram"],
    "instagram": [
        # "Zuck is a cuck",
        "Zuck is a chicken",
        "\U0001F445\U0001F923", # tongue/laugh
        "If Zuck my \U0001F445 really wants a lesson in why there are weight categories in fighting so badly, I could just head over to his house next week and teach him a lesson he won’t soon forget",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Competition is fine, cheating is not",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram"],
    "threads": [
        # "Zuck is a cuck",
        "Zuck is a chicken",
        "\U0001F445\U0001F923", # tongue/laugh
        "If Zuck my \U0001F445 really wants a lesson in why there are weight categories in fighting so badly, I could just head over to his house next week and teach him a lesson he won’t soon forget",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Competition is fine, cheating is not",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram"],
    " meme": [
        "\U0001F923\U0001F525", # laugh/fire
        "\U0001F923\U0001F923", # laugh/laugh
        "\U0001F923\U0001F4AF", # laugh/100
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "\U0001F445\U0001F923", # tongue/laugh
        "The meme community has high standards!",
        "Have you considered a career in comedy?",
        "Let that sink in",
        "That’s what she said"],
    " fun": [
        "\U0001F923\U0001F525", # laugh/fire
        "\U0001F923\U0001F923", # laugh/laugh
        "\U0001F923\U0001F4AF", # laugh/100
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "\U0001F445\U0001F923", # tongue/laugh
        "The meme community has high standards!",
        "Have you considered a career in comedy?",
        "Funny cause it’s true",
        "That’s what she said"],
    "babylon": [
        "\U0001F923\U0001F525", # laugh/fire
        "\U0001F923\U0001F923", # laugh/laugh
        "\U0001F923\U0001F4AF", # laugh/100
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "Funny cause it’s true",
        "RAGE FOR THE MACHINE!!"],
    "block": [
        "I’m having a good time blocking people who complain that blocking is going away \U0001F923",
        "Negative feedback is a good thing",
        "Negative feedback received on this platform is great for reducing ego-based errors",
        "I appreciate the note. Frankly, negative feedback is good. Keeps ego in check.",
        "Frankly, I love the negative feedback on this platform. Vastly preferable to some sniffy censorship bureau!",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram"],
    "tweet": [
        "Concerning",
        "!",
        "That’s what she said",
        "Whatever you say, cutie \U0001F979",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Haha that would sickkk",
        "Better to talk to people than communicate via tweet."],
    "business": [
        "\U0001F3AF", # bullseye
        "\U0001F4AF", # 100
        "\U0001F9BE", # mechanical arm
        "Accurate",
        "Exactly",
        "Really",
        "Obviously",
        "True",
        "A trillion dollar market cap for this platform is not out of the question",
        "I do hope to succeed in business \U0001F91E"],
    "career": [
        "\U0001F3AF", # bullseye
        "\U0001F4AF", # 100
        "\U0001F9BE", # mechanical arm
        "Accurate",
        "Exactly",
        "Really",
        "Obviously",
        "True",
        "A trillion dollar market cap for this platform is not out of the question",
        "I do hope to succeed in business \U0001F91E"],
    "comedy": [
        "That’s what she said",
        "Haha that would sickkk",
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "Have you considered a career in comedy?",
        "Knock knock  \nWho’s there?  \nKnutsēk  \nNutsack who?  \nKnutsēk Tæbag"],
    "alex gibney": ["It’s a hit piece", "He’s the worst, sorry."],
    "documentary": ["It’s a hit piece", "Concerning"],
    "film": ["It’s a hit piece", "Concerning"],
    "movie": ["It’s a hit piece", "Concerning"],
    "batman": [
        "He loves bats next-level.",
        "Civilization is more fragile than it would seem"],
    " bats": ["He loves bats next-level."],
    "concerning": ["Yeah"],
    "war ": [
        "I prefer peace, but if they want war, they will get it",
        "It’s a civilized form of war. Men love war."],
    "peace": [
        "I prefer peace, but if they want war, they will get it",
        "It’s a civilized form of war. Men love war."],
    " old": [
        "I keep forgetting that you’re still alive",
        "The gerontocracy is real"],
    "boomer": [
        "I keep forgetting that you’re still alive",
        "The gerontocracy is real"],
    "biden": [
        "Concerning",
        "Strange",
        "Wow",
        "Odd",
        "I keep forgetting that you’re still alive",
        "The gerontocracy is real"],
    "pelosi": [
        "Super concerning",
        "Strange",
        "Wow",
        "Odd",
        "That’s what she said",
        "The gerontocracy is real"],
    "sanders": [
        "I keep forgetting that you’re still alive",
        "The gerontocracy is real"],
    "soros": [
        "Soros reminds me of Magneto",
        "He wants to erode the very fabric of civilization. Soros hates humanity.",
        "Extremely concerning",
        "Strange",
        "Wow",
        "Odd",
        "The gerontocracy is real"],
    "zuck": [
        "Zuck is a cuck",
        "Zuck is a chicken",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Competition is fine, cheating is not",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram",
        "\U0001F445\U0001F923", # tongue/laugh
        "If Zuck my \U0001F445 really wants a lesson in why there are weight categories in fighting so badly, I could just head over to his house next week and teach him a lesson he won’t soon forget",
        "I’m gonna bang on his door tomorrow and demand to fight",
        "Voglio ringraziare il ministro Sangiuliano per la gentilezza e la disponibilità nel voler organizzare un evento di intrattenimento, culturale e di beneficenza in Italia. Volevamo promuovere la storia dell’Antica Roma con il supporto di esperti e allo stesso tempo raccogliere soldi per i veterani americani e gli ospedali pediatrici in Italia. Zuckerberg ha rifiutato l’offerta perché non è interessato a questo approccio. Vuole solo combattere se è la UFC organizzare l’incontro. Io comunque sono sempre pronto a combattere \u2694\uFE0F",
        "He can’t eat at chic fil a because that would be cannibalism",],
    " tate": [
        "Super concerning",
        "Strange",
        "Wow",
        "Odd",
        "To sleep with women endlessly without love is a cursed and hollow life"],
    "linda": ["CEO is fake title."],
    "yaccarino": ["CEO is fake title."],
    " ceo": ["CEO is fake title."],
    "judo": [
        "Although very dated now, I trained in judo, Kyokushin (full contact) & no rules streetfighting.",
        "Am lifting weights throughout the day, preparing for the fight. Don’t have time to work out, so I just bring them to work.",
        "It’s a civilized form of war. Men love war.",
        "Product testing & working out kills two birds with one stone!",
        "I build muscle fast. Physical endurance is my weak spot.",
        "Exact date is still in flux. I’m getting an MRI of my neck & upper back tomorrow.\n\nMay require surgery before the fight can happen. Will know this week.",
        "I have this great move that I call “The Walrus”, where I just lie on top of my opponent & do nothing",
        "If Zuck my \U0001F445 really wants a lesson in why there are weight categories in fighting so badly, I could just head over to his house next week and teach him a lesson he won’t soon forget",
        "I’m gonna bang on his door tomorrow and demand to fight",
        "He can’t eat at chic fil a because that would be cannibalism"],
    " ufc": [
        "Although very dated now, I trained in judo, Kyokushin (full contact) & no rules streetfighting.",
        "Am lifting weights throughout the day, preparing for the fight. Don’t have time to work out, so I just bring them to work.",
        "It’s a civilized form of war. Men love war.",
        "Product testing & working out kills two birds with one stone!",
        "I build muscle fast. Physical endurance is my weak spot.",
        "Exact date is still in flux. I’m getting an MRI of my neck & upper back tomorrow.\n\nMay require surgery before the fight can happen. Will know this week.",
        "I have this great move that I call “The Walrus”, where I just lie on top of my opponent & do nothing",
        "If Zuck my \U0001F445 really wants a lesson in why there are weight categories in fighting so badly, I could just head over to his house next week and teach him a lesson he won’t soon forget",
        "I’m gonna bang on his door tomorrow and demand to fight",
        "He can’t eat at chic fil a because that would be cannibalism"],
    "fight": [
        "Zuck is a cuck",
        "Zuck is a chicken",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Although very dated now, I trained in judo, Kyokushin (full contact) & no rules streetfighting.",
        "Am lifting weights throughout the day, preparing for the fight.\n\nDon’t have time to work out, so I just bring them to work.",
        "It’s a civilized form of war. Men love war.",
        "Product testing & working out kills two birds with one stone!",
        "I build muscle fast. Physical endurance is my weak spot.",
        "Exact date is still in flux. I’m getting an MRI of my neck & upper back tomorrow.\n\nMay require surgery before the fight can happen. Will know this week.",
        "I have this great move that I call “The Walrus”, where I just lie on top of my opponent & do nothing",
        "If Zuck my \U0001F445 really wants a lesson in why there are weight categories in fighting so badly, I could just head over to his house next week and teach him a lesson he won’t soon forget",
        "I’m gonna bang on his door tomorrow and demand to fight",
        "He can’t eat at chic fil a because that would be cannibalism"],
    "parent": [
        "Interesting",
        "!!",
        "Concerning",
        "Parents don’t realize the Soviet level of indoctrination that their children are receiving in elite high schools & colleges!"],
    "school": [
        "Interesting",
        "!!",
        "Concerning",
        "Strange",
        "Wow",
        "Parents don’t realize the Soviet level of indoctrination that their children are receiving in elite high schools & colleges!"],
    "college": [
        "Interesting",
        "!!",
        "Concerning",
        "Strange",
        "Wow",
        "Parents don’t realize the Soviet level of indoctrination that their children are receiving in elite high schools & colleges!"],
    "child": [
        "Interesting",
        "!!",
        "Concerning",
        "Parents don’t realize the Soviet level of indoctrination that their children are receiving in elite high schools & colleges!"],
    "algorithm": [
        "Prepare to be disappointed at first when our algorithm is made open source next week, but it will improve rapidly!",
        "Announcing formation of @xAI to understand reality"],
    "open source": ["Prepare to be disappointed at first when our algorithm is made open source next week, but it will improve rapidly!"],
    # "love": [
    #     "Some hate humanity, but I love humanity so much",
    #     "falling in love hits different when you know they’re a paid actor sent by the CIA to distract you from dedicating your life to dismantling the government"],
    # " hate": ["Some hate humanity, but I love humanity so much"],
    "human": [
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "Some hate humanity, but I love humanity so much",
        "Although there are some bad things in the world, remember that there are many good things too",
        "Civilization is more fragile than it would seem",
        "He wants to erode the very fabric of civilization. Soros hates humanity.",
        "Very important to make new humans.",
        "Very important to make new humans.\n\nNo new humans means no humanity.",
        "To heir is human,  \nTo procreate divine"],
    "population": [
        "Vox Populi Vox Dei",
        "Demographics is destiny",
        "He wants to erode the very fabric of civilization. Soros hates humanity.",
        "Civilization is more fragile than it would seem",
        "Very important to make new humans.",
        "Very important to make new humans.\n\nNo new humans means no humanity.",
        "To heir is human,  \nTo procreate divine"],
    "government": [
        "Does seem asymmetric",
        "falling in love hits different when you know they’re a paid actor sent by the CIA to distract you from dedicating your life to dismantling the government",
        "By the way, I am actually a socialist.",
        "The intolerant left is driving people right"],
    "russia": [
        "Parents don’t realize the Soviet level of indoctrination that their children are receiving in elite high schools & colleges!",
        "Nice doors"],
    "paranoi": ["falling in love hits different when you know they’re a paid actor sent by the CIA to distract you from dedicating your life to dismantling the government"],
    "journalis": [
        "You represent the problem: journalists who think they are the only source of legitimate information. That’s the big lie.",
        "Twitter is a serious danger to their ability to control the narrative",
        "Some of the smartest people I know actively believe the press … amazing",
        "press@twitter.com now auto responds with \U0001F4A9",
        "They posted my exact real-time location, basically assassination coordinates"],
    "dox": ["They posted my exact real-time location, basically assassination coordinates"],
    "news": [
        "You represent the problem: journalists who think they are the only source of legitimate information. That’s the big lie.",
        "Twitter is a serious danger to their ability to control the narrative",
        "Some of the smartest people I know actively believe the press … amazing",
        "press@twitter.com now auto responds with \U0001F4A9"],
    "nyt ": [
        "You represent the problem: journalists who think they are the only source of legitimate information. That’s the big lie.",
        "Twitter is a serious danger to their ability to control the narrative",
        "Some of the smartest people I know actively believe the press … amazing",
        "press@twitter.com now auto responds with \U0001F4A9",
        "The real tragedy of @NYTimes is that their propaganda isn’t even interesting"],
    "new york times": [
        "You represent the problem: journalists who think they are the only source of legitimate information. That’s the big lie.",
        "Twitter is a serious danger to their ability to control the narrative",
        "Some of the smartest people I know actively believe the press … amazing",
        "press@twitter.com now auto responds with \U0001F4A9",
        "The real tragedy of @NYTimes is that their propaganda isn’t even interesting"],
    "washington post": [
        "You represent the problem: journalists who think they are the only source of legitimate information. That’s the big lie.",
        "Twitter is a serious danger to their ability to control the narrative",
        "Some of the smartest people I know actively believe the press … amazing",
        "press@twitter.com now auto responds with \U0001F4A9"],
    "cbc": ["69% Government-Funded Media"],
    "depress": [
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram",
        "Occasional use of Ketamine is a much better option, in my opinion. I have a prescription for when my brain chemistry sometimes goes super negative."],
    "ketamine": [
        "Make my words.",
        "Yes!! \U0001F923\U0001F923",
        "Try it, but don’t trust it yet.",
        "Occasional use of Ketamine is a much better option, in my opinion. I have a prescription for when my brain chemistry sometimes goes super negative.",
        "\U0001F4AF\n\nOnly thing more insane than a nazi is a nazi on meth"],
    "drug": [
        "Make my words.",
        "Yes!! \U0001F923\U0001F923",
        "Try it, but don’t trust it yet.",
        "Occasional use of Ketamine is a much better option, in my opinion. I have a prescription for when my brain chemistry sometimes goes super negative.",
        "\U0001F4AF\n\nOnly thing more insane than a nazi is a nazi on meth"],
    "elon": [
        "\U0001F923\U0001F525", # laugh/fire
        "\U0001F923\U0001F923", # laugh/laugh
        "\U0001F3AF", # bullseye
        "\U0001F4AF", # 100
        "\U0001F9BE", # mechanical arm
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "\U0001F445\U0001F923", # tongue/laugh
        "Accurate",
        "Precisely",
        "Exactly",
        "Really",
        "Obviously",
        "True",
        "Interesting",
        "\#SoBrave",
        "Parody & reality are becoming indistinguishable",
        "Concerning",
        "Extremely concerning",
        "Super concerning",
        "Strange",
        "It makes no sense",
        "Wow",
        "Odd",
        "That’s what she said",
        "Whatever you say, cutie \U0001F979",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Haha that would sickkk",
        "Negative feedback is a good thing",
        "Negative feedback received on this platform is great for reducing ego-based errors",
        "I appreciate the note. Frankly, negative feedback is good. Keeps ego in check.",
        "Frankly, I love the negative feedback on this platform. Vastly preferable to some sniffy censorship bureau!",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram",
        "I get all my opinions from Twitter",
        "You are free to be your true self here",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "I never take notes",
        "It’s kinda flattering to be insulted on this site tbh",
        "I hope this platform increasingly brings you joy & elucidation",
        "We are hell bent on making this platform the best place on Earth for great content creators!",
        "You’re terrible & I love you\n\n*not terrible",
        "Sometimes, when you learn about something, you think you have it",
        "Haha what a tool",
        "Incompetence, in the limit, is indistinguishable from sabotage",
        "Why does ur pp look like u just came?",
        "You rang? \U0001F608",
        "A latte is really just an excuse for adults to order warm milk without sounding like a baby",
        "Honey is neither animal, plant or fungus\n\n*nor",
        "Although very dated now, I trained in judo, Kyokushin (full contact) & no rules streetfighting.",
        "You’re welcome namaste \U0001F64F",
        "I prefer peace, but if they want war, they will get it",
        "Nice doors",
        "Make my words.",
        "Testosterone rocks ngl",
        "A few times a year, I take Sunday afternoons off",
        "I build muscle fast. Physical endurance is my weak spot."],
    "musk": [
        "\U0001F923\U0001F525", # laugh/fire
        "\U0001F923\U0001F923", # laugh/laugh
        "\U0001F3AF", # bullseye
        "\U0001F4AF", # 100
        "\U0001F9BE", # mechanical arm
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "\U0001F445\U0001F923", # tongue/laugh
        "Accurate",
        "Precisely",
        "Exactly",
        "Really",
        "Obviously",
        "True",
        "Interesting",
        "\#SoBrave",
        "Parody & reality are becoming indistinguishable",
        "Concerning",
        "Extremely concerning",
        "Super concerning",
        "Strange",
        "It makes no sense",
        "Wow",
        "Odd",
        "That’s what she said",
        "Whatever you say, cutie \U0001F979",
        "Haha that would sickkk",
        "Negative feedback is a good thing",
        "Negative feedback received on this platform is great for reducing ego-based errors",
        "I appreciate the note. Frankly, negative feedback is good. Keeps ego in check.",
        "Frankly, I love the negative feedback on this platform. Vastly preferable to some sniffy censorship bureau!",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram",
        "I get all my opinions from Twitter",
        "You are free to be your true self here",
        "X will become the most valuable brand on Earth. Make my words.",
        "\U0001D54F as humanity’s  \ncollective  \nconsciousness",
        "I never take notes",
        "It’s kinda flattering to be insulted on this site tbh",
        "I hope this platform increasingly brings you joy & elucidation",
        "We are hell bent on making this platform the best place on Earth for great content creators!",
        "You’re terrible & I love you\n\n*not terrible",
        "Sometimes, when you learn about something, you think you have it",
        "Haha what a tool",
        "Incompetence, in the limit, is indistinguishable from sabotage",
        "Why does ur pp look like u just came?",
        "You rang? \U0001F608",
        "A latte is really just an excuse for adults to order warm milk without sounding like a baby",
        "Honey is neither animal, plant or fungus\n\n*nor",
        "Although very dated now, I trained in judo, Kyokushin (full contact) & no rules streetfighting.",
        "You’re welcome namaste \U0001F64F",
        "I prefer peace, but if they want war, they will get it",
        "Nice doors",
        "Make my words.",
        "Testosterone rocks ngl",
        "A few times a year, I take Sunday afternoons off",
        "I build muscle fast. Physical endurance is my weak spot."],
    "horny": [
        "That’s what she said",
        "Whatever you say, cutie \U0001F979",
        "You rang? \U0001F608",
        "\U0001F6AC",
        "\U0001F445\U0001F923", # tongue/laugh
        "Her limbic resonance skill is exceptional",
        "To sleep with women endlessly without love is a cursed and hollow life"],
    "taylor swift": [
        "You rang? \U0001F608",
        "\U0001F6AC",
        "Her limbic resonance skill is exceptional"],
    " law": ["Lawsuit time."],
    "microsoft": ["Lawsuit time."],
    " poo ": ["Yes!! \U0001F923\U0001F923"],
    " poop": ["Yes!! \U0001F923\U0001F923"],
    "?$": [
        "Simultaneously, an interesting question and a tongue twister!",
        "That’s what she said",
        "Whatever you say, cutie \U0001F979",
        "Why does ur pp look like u just came?",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Haha that would sickkk",
        "Interesting",
        "!!",
        "Concerning",
        "Extremely concerning",
        "Super concerning",
        "Strange",
        "It makes no sense",
        "Wow",
        "Odd",
        "Make my words.",
        "In the spirit of self-awareness, what are you?"],
    "notenoughmuskspam": [
        "\U0001F3AF", # bullseye
        "\U0001F4AF", # 100
        "\U0001F9BE", # mechanical arm
        "\U0001F4AF\U0001F3AF\U0001F923", # 100/bullseye/laugh
        "\U0001F445\U0001F923", # tongue/laugh
        "Accurate",
        "Precisely",
        "Exactly",
        "Really",
        "Obviously",
        "True",
        "Interesting",
        "\#SoBrave",
        "Parody & reality are becoming indistinguishable",
        "!!",
        "Concerning",
        "Extremely concerning",
        "Super concerning",
        "Strange",
        "It makes no sense",
        "Wow",
        "Odd",
        "That’s what she said",
        "Make my words.",
        "Whatever you say, cutie \U0001F979",
        "I propose a literal dick measuring contest \U0001F4CF",
        "Haha that would sickkk",
        "Negative feedback is a good thing",
        "Negative feedback received on this platform is great for reducing ego-based errors",
        "I appreciate the note. Frankly, negative feedback is good. Keeps ego in check.",
        "Frankly, I love the negative feedback on this platform. Vastly preferable to some sniffy censorship bureau!",
        "It is infinitely preferable to be attacked by strangers on Twitter, than indulge in the false happiness of hide-the-pain Instagram",
        "I get all my opinions from Twitter",
        "In the spirit of self-awareness, what are you?"]
    # "trans": ["My pronouns are Prosecute/Fauci", "Pronouns suck"],
    # boring company
    # microservices just add bloat
}
